// <auto-generated />
namespace byggemarked.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class complete : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(complete));
        
        string IMigrationMetadata.Id
        {
            get { return "202011101837107_complete"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
